name: flexus_ext
description: A new Flutter project.
version: 3.3.18
homepage: https://dilexusit.com

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #Dev
  get: ^4.6.5
  package_info_plus: ^1.4.2
  network_to_file_image: ^4.0.1

  #Firebase
  firebase_auth: ^3.3.19
  firebase_storage: ^10.2.17

  #UI
  font_awesome_flutter: ^10.1.0

  #Image
  image_picker: ^0.8.5+3
  image_cropper: ^2.0.3

  #Form:
  flutter_form_builder: ^7.2.1
  form_builder_validators: ^8.1.1

  #Auth
  crypto: ^3.0.1
  google_sign_in: ^5.3.3
  flutter_facebook_auth: ^4.3.4+2
  sign_in_with_apple: ^4.0.0

# flexus_core:
#   path: ../flexus_core/
  #Flexus Core
  flexus_core: ^3.3.35



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
